## CHARGEMENT et Exploration des DONN√âES

In [2]:
#Importation des bibs
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Chargement du dataset
dataset_path = r"C:\Users\VECTUS\DL_For_SOC_Estimation\datasets\concat_data.csv"

# Lecture du CSV
df = pd.read_csv(dataset_path, delimiter=",")

# V√©rification des colonnes disponibles
print("\U0001F4CA Colonnes d√©tect√©es :", df.columns)

# Aper√ßu des premi√®res lignes
display(df.head())

üìä Colonnes d√©tect√©es : Index(['Heure', 'Courant', 'Tension', 'Cellule_min', 'Cellule_max', 'Temp1',
       'Temp4', 'SOC'],
      dtype='object')

   Heure  Courant  Tension  Cellule_min  Cellule_max  Temp1  Temp4   SOC
0  0.000     59.1      390         4057         4067     21     20  79.4
1  0.809     59.1      390         4058         4068     21     20  79.4
2  1.650     59.1      390         4057         4068     21     20  79.4
3  2.480     59.0      390         4057         4068     21     20  79.4
4  3.256     58.9      390         4058         4069     21     20  79.4

In [3]:
# V√©rification des valeurs manquantes
print("\n V√©rification des valeurs manquantes :")
print(df.isnull().sum())

# Statistiques descriptives
display(df.describe())

 V√©rification des valeurs manquantes :
Heure          0
Courant        0
Tension        0
Cellule_min    0
Cellule_max    0
Temp1          0
Temp4          0
SOC            0
dtype: int64

,Heure,Courant,Tension,Cellule_min,Cellule_max,Temp1,Temp4,SOC
count,1267.000000,1267.000000,1267.000000,1267.000000,1267.000000,1267.000000,1267.000000,1267.000000
mean,175.660259,22.526046,381.974743,3971.490134,3985.235201,20.389897,19.331492,76.592344
std,109.105756,20.776457,6.466049,69.367560,67.308138,0.668278,0.559828,3.366041
min,0.000000,-4.200000,375.000000,3902.000000,3917.000000,20.000000,19.000000,73.700000
25%,84.615000,8.900000,377.000000,3924.000000,3939.000000,20.000000,19.000000,74.200000
50%,169.336000,15.000000,378.000000,3934.000000,3949.000000,20.000000,19.000000,74.800000
75%,254.047500,51.200000,390.000000,4063.500000,4073.500000,21.000000,20.000000,80.000000
max,431.234000,59.200000,394.000000,4100.000000,4111.000000,22.000000,21.000000,83.900000

### Description des colonnes du fichier CSV

| Nom de la colonne | Description |
|-------------------|-------------|
| **Heure** | Temps en secondes depuis le d√©but de la mesure |
| **Courant** | Valeur du courant de la batterie haute tension (en amp√®res) |
| **Tension** | Tension de la batterie haute tension (en volts) |
| **Cellule_min** | Tension minimale parmi les cellules de la batterie HV (en millivolts) |
| **Cellule_max** | Tension maximale parmi les cellules de la batterie HV (en millivolts) |
| **Temp1** | Temp√©rature relev√©e √† un premier point de la batterie HV (en ¬∞C) |
| **Temp4** | Temp√©rature relev√©e √† un quatri√®me point de la batterie HV (en ¬∞C) |
| **SOC** | √âtat de charge de la batterie en pourcentage |